//
// JobAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class JobAPI {
    /**
     Get Job
     
     - parameter description: (query) Job Description 
     - parameter page: (query) Page Number 
     - parameter location: (query) Location (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getJob(description: String, page: Int, location: String? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: [Job]?,_ error: Error?) -> Void)) {
        getJobWithRequestBuilder(description: description, page: page, location: location).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Job
     - GET /positions.json
     - parameter description: (query) Job Description 
     - parameter page: (query) Page Number 
     - parameter location: (query) Location (optional)
     - returns: RequestBuilder<[Job]> 
     */
    open class func getJobWithRequestBuilder(description: String, page: Int, location: String? = nil) -> RequestBuilder<[Job]> {
        let path = "/positions.json"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "description": description.encodeToJSON(), 
            "location": location?.encodeToJSON(), 
            "page": page.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<[Job]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
